[tool.poetry]
name = "mxq-data-science-db"
version = "v1.2.10"
description = "Package to manage DBs and Models"
authors = ["Miguel Hentoux"]
readme = "README.md"
packages = [{include = "mxq_data_science_db"}]

[tool.poetry.dependencies]
python = "^3.10"
pymysql = "^1.1.0"
pandas = "^2.1.0"
boto3 = "^1.28.43"
sqlalchemy = "^2.0.21"
pymsteams = "^0.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
