[build-system]
requires = [
    "setuptools", 
    "setuptools-scm"
]
build-backend = "setuptools.build_meta"

[project]
name = "generator_cucumber"
description = "Generation gitlab/github => .feature file"
readme = "README_PY.md"
keywords= [
    "python",
    "cucmber",
    "generator"
]
authors = [
    {name = "Dmitry Shibikin", email = "dmitry.shibikin@yandex.ru"}
]
requires-python = ">=3.8"

license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities"
]
version = "0.0.20"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Repository = "https://gitlab.com/python_lib/generator_cucumber"
Homepage = "https://gitlab.com/python_lib/generator_cucumber"
Documentation = "https://bdd-generator.readthedocs.io/ru/latest/"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
exclude = ["docs*", "tests*", "example"]

[project.scripts]
bdd = "generator_cucumber:hello_world"