[tool.poetry]
name = "aporacle"
version = "0.0.149"
description = ""
authors = ["Makhosonke Morafo <makhosonke@komokun.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
schedule = "^1.2.1"
cachetools = "^5.3.3"
pandas = "^2.2.1"
google-cloud-storage = "^2.16.0"
komoutils = "^0.0.230"
boto3 = "^1.34.151"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"