[project]
name = "osagent"
version = "0.1.1"
description = "osagent"
authors = [
    {name = "XLANG"},
]
dependencies = [
    "pip>=24.2",
    "python-xlib>=0.33",
    "lxml>=5.2.2",
    "pyautogui>=0.9.54",
    "requests>=2.32.3",
    "flask>=3.0.3",
    "numpy<2",
    "gymnasium>=0.29.1",
    "playwright>=1.45.1",
    "pydrive>=1.3.1",
    "requests-toolbelt>=1.0.0",
    "rapidfuzz>=3.9.5",
    "beautifulsoup4>=4.12.3",
    "pandas>=2.2.2",
    "formulas>=1.2.8",
    "cssselect>=1.2.0",
    "xmltodict>=0.13.0",
    "openpyxl>=3.1.5",
    "pypdf2>=3.0.1",
    "PyMuPDF>=1.24.9",
    "borb>=2.1.24",
    "easyocr>=1.7.1",
    "python-docx>=1.1.2",
    "odfpy>=1.4.1",
    "pdfplumber>=0.11.2",
    "mutagen>=1.47.0",
    "pypdf>=4.3.1",
    "python-pptx>=0.6.23",
    "pyacoustid>=1.3.0",
    "ImageHash>=4.3.1",
    "librosa>=0.10.2.post1",
    "fastdtw>=0.3.4",
    "psutil>=6.0.0",
    "tqdm>=4.66.4",
    "boto3>=1.34.151",
    "backoff>=2.2.1",
    "dashscope>=1.20.3",
    "google-generativeai>=0.7.2",
    "openai>=1.37.1",
    "tiktoken>=0.7.0",
    "groq>=0.9.0",
    "sounddevice>=0.4.7",
    "pygame>=2.6.0",
    "pynput>=1.7.7",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
mac = [
    "pyobjc-framework-ApplicationServices>=10.3.1",
]
win = [
    "pywinauto>=0.6.8",
]
all = ["foo[mac,win]"]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true
