[project]
name = "simple_keystore"
version = "0.2.0"
description = "\"A simple encrypted key storage\""
authors = [
    { name = "Paul", email = "paul@nowfree.org" },
]
dependencies = [
    "cryptography>=43.0.0",
    "tabulate>=0.9.0",
]
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Repository = "https://github.com/eyecantell/simple_keystore"
Issues = "https://github.com/eyecantell/simple_keystore/issues"

[project.scripts]
my-command = "manage_keys.py:main"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = []

[tool.ruff]
line-length = 120

[tool.ruff.lint.isort]
combine-as-imports = true
