[tool.poetry]
name = "apparat"
version = "0.2.0"
description = "This is the machine description framework"
authors = ["Frans FÃ¼rst <frans.fuerst+gitlab@protonmail.com>"]
repository = "https://projects.om-office.de/frans/apparat.git"
readme = "Readme.md"
packages = [
  {include = "apparat"},
]


# see https://pypi.org/project/poetry-bumpversion
# poetry version patch [--dry-run]
[tool.poetry_bumpversion.file."apparat/__init__.py"]


[tool.poetry.dependencies]
python = ">=3.10.4,<4"
asyncinotify = "^4.0"


[tool.poetry.dev-dependencies]
asyncssh = "^2"
black = "^22"
isort = "^5"
pytest = "^7"
pytest-cov = "^3"
mypy = "^1.5"
pylint = "^2"
ipython = "^8"
twine = "^4"
pre-commit = "^3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
fast = true
exclude = '''
(                       # exclude a few common directories in the root of the project
  /(                    # note that this has to be done in .pre-commit-config.yaml, too
    untracked
    | \.git
    | \.pytest_cache
    | \.mypy_cache
    | \.venv
    | \.container_home_dir
    | untracked
    | build
    | dist
  ))
'''


[tool.isort]
profile = "black"
skip_glob = [".venv", ".container_home_dir"]


[tool.mypy]
python_version = "3.10"
strict="True"
disallow_untyped_defs = "True"
disallow_any_unimported = "True"
no_implicit_optional = "True"
check_untyped_defs = "True"
warn_return_any = "True"
warn_unused_ignores = "True"
show_error_codes = "True"
exclude = [
    '\.venv',
    'tests'
]
