[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mbutil_zyx"
authors = [
  { name="Lars Maxfield" },
  ]
description = "MBUtil with ZYX scheme"
readme = "README.md"
requires-python = ">=3"
version = "0.4.0"
license = {file = "LICENSE.md"}
keywords = ["mbutil", "zyx", "vips", "libvips", "pyvips", "dzsave"]
classifiers = [
    "Programming Language :: Python",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent"]

[project.urls]
Homepage = "https://github.com/larsmaxfield/mbutil_zyx"
Issues = "https://github.com/larsmaxfield/mbutil_zyx"
