[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "loe_simp_app_fw"
version = "2.6.13"
authors = [
  { name="loeeeee", email="95266635+loeeeee@users.noreply.github.com" },
]
description = "A super simple python app framework that includes a logger and a config manager. Also usable in jupyter notebook."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
  "pyyaml",
  "requests"
]

[project.urls]
Homepage = "https://github.com/loeeeee/loe-simp-app-fw"
Issues = "https://github.com/loeeeee/loe-simp-app-fw/issues"

[tool.hatch.build.targets.sdist]
exclude = [
  "/src/tests",
]