[build-system]
requires = [
    "pandas==2.2.2",
    "rdkit==2023.9.6",
    "numpy==1.26.4",
    "XlsxWriter==3.2.0",
    "openpyxl==3.1.5",
    "colorama==0.4.6",
]

build-backend = "setuptools.build_meta"