

[tool.poetry]
name = "clear-skies-twilio"
version = "0.9.3"
description = "clearskies bindings for working with Twilio"
authors = [
    "Conor Mancone <cmancone@gmail.com>",
]
repository = "https://github.com/cmancone/clearskies-twilio"
license = "MIT"
readme = "./README.md"
packages = [
    { include = "clearskies_twilio", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
clear-skies = "^1.19.24"
twilio = "^9.0.5"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"
black = "^23.3.0"
pytest = "^7.4.0"


[tool.poetry.extras]

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
