[tool.black]
line-length = 100
target-version = ['py310']
skip-string-normalization = true
exclude='''
/(
    src/show_dialog/ui/forms
  | \.venv.*
  | \venv.*
)/
'''

[tool.isort]
line_length = 100
profile = 'black'
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
skip = ['src/show_dialog/ui/forms']
skip_glob = ['**/.venv*', '**/venv*']

[tool.mypy]
# Technical notes on exclusions:
# 1 The regex for all folders needs to be in a one line string.
# 2 The `.` doesn't need to be escaped. Escape with `\\.` for a fully compatible regex.
exclude = '^venv*|^.venv*|.git|.eggs|build|dist|.cache|.pytest_cache|.mypy_cache|.vscode|.idea|tasks.py'
python_version = '3.10'
warn_return_any = true
warn_unused_configs = true
# Disable the warning below, from type hinting variables in a function.
# By default, the bodies of untyped functions are not checked, consider using --check-untyped-defs
disable_error_code = 'annotation-unchecked'

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ['invoke']

[tool.pytest.ini_options]
testpaths = ['tests']

[build-system]
requires = ['flit_core >=3.2,<4']
build-backend = 'flit_core.buildapi'

[project]
name = 'pytest-params'
version = '0.1.0'
description = 'Simplified pytest test case parameters.'
readme = 'README.md'
authors = [{name = 'Joao Coelho'}]
license = {file = 'LICENSE'}
dependencies = ['pytest>=7.0.0']
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Framework :: Pytest" ,
]

[project.urls]
Home = 'https://github.com/joaonc/pytest-params'

[tool.flit.module]
name = 'pytest_params'
