[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rship-sdk"
version = "0.1.7"
authors = [
  { name="Max Fletcher", email="max@lucid.rocks" },
  { name="Trevor Sargent", email="trev@lucid.rocks" },
]
description = "The Rship SDK in python"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "myko",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/lucid-rocks/rocketship"
Issues = "https://github.com/lucid-rocks/rocketship/issues"
Docs = "https://docs.rship.io"