[tool.poetry]
name = "generic-consumer"
version = "0.15.8"
description = ""
authors = ["Mister Nyan <michael.edmund.wong@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
simple-chalk = "^0.1.0"
fun-things = "^0.24.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
